#/usr/bin/env bash

#######################################
# Common setup. Init MacOS compatibility
# variables.
# Globals:
#   READLINK
#######################################
function common_setup
{
    # On macOS, use GNU readlink from 'coreutils' package in Homebrew/MacPorts
    if [ "$(uname -s)" = "Darwin" ] ; then
        READLINK=greadlink
    else
        READLINK=readlink
    fi
}

#######################################
# Error echo wrapper
#######################################
function error
{
    echo "${0##*/}: ${1}" >&2
}

#######################################
# Error then exit wrapper
# Arguments:
#   string to print before exit
#   (optional) int error code
#######################################
function die
{
    error "$1"
    exit "${2:--1}"
}

#######################################
# Save bash options. Must be called
# before a corresponding `restore_bash_options`.
#######################################
function save_bash_options
{
    OLDSTATE=$(set +o)
}

#######################################
# Restore bash options. Must be called
# after a corresponding `save_bash_options`.
#######################################
function restore_bash_options
{
    set +vx; eval "$OLDSTATE"
}

#######################################
# Emit a fresh Chipyard env.sh.
# Arguments:
#   path to env.sh
#######################################
function write_env_sh
{
    local env_file=$1
    local env_dir
    local tmp_file

    env_dir=$(dirname "$env_file")
    tmp_file=$(mktemp "$env_dir/.env.sh.tmp.XXXXXX")

    cat > "$tmp_file" <<'EOT'
# Auto-generated by Chipyard setup scripts.
# Source this file from bash/zsh to activate the local Chipyard environment.

__chipyard_env_fail() {
    echo "env.sh: $1" >&2
    return 1 2>/dev/null || exit 1
}

if [ -n "${BASH_SOURCE[0]:-}" ]; then
    __chipyard_env_source="${BASH_SOURCE[0]}"
elif [ -n "${ZSH_VERSION:-}" ]; then
    __chipyard_env_source="${(%):-%N}"
else
    __chipyard_env_source="$0"
fi

__DIR="$(CDPATH= cd -- "$(dirname -- "$__chipyard_env_source")" && pwd)" || __chipyard_env_fail "failed to locate Chipyard directory"

__chipyard_prepend_path() {
    if [ -n "$1" ] && [ -d "$1" ]; then
        case ":$PATH:" in
            *":$1:"*) ;;
            *) PATH="$1${PATH:+:$PATH}" ;;
        esac
    fi
}

__chipyard_prepend_path "$__DIR/bin"
__chipyard_prepend_path "$__DIR/software/firemarshal"

if [ -d "$__DIR/.conda-env" ]; then
    if [ -f "$__DIR/.conda-env/etc/profile.d/conda.sh" ]; then
        . "$__DIR/.conda-env/etc/profile.d/conda.sh"
    else
        __chipyard_env_fail "missing $__DIR/.conda-env/etc/profile.d/conda.sh; rerun ./build-setup.sh"
    fi

    conda activate "$__DIR/.conda-env" || __chipyard_env_fail "failed to activate $__DIR/.conda-env"
fi

if [ "${CONDA_PREFIX:-}" = "$__DIR/.conda-env" ]; then
    __chipyard_env_name="${CHIPYARD_ENV_NAME:-EC}"
    __chipyard_prompt="($__chipyard_env_name) "
    __chipyard_old_prompt="${CONDA_PROMPT_MODIFIER:-}"

    export CONDA_DEFAULT_ENV="$__chipyard_env_name"
    export CONDA_PROMPT_MODIFIER="$__chipyard_prompt"

    case "$-" in
        *i*)
            case "${PS1:-}" in
                "$__chipyard_prompt"*) ;;
                "$__chipyard_old_prompt"*) PS1="$__chipyard_prompt${PS1#"$__chipyard_old_prompt"}" ;;
                *) PS1="$__chipyard_prompt${PS1:-}" ;;
            esac
            ;;
    esac
fi

if [ -r "$__DIR/scripts/fix-open-files.sh" ]; then
    . "$__DIR/scripts/fix-open-files.sh"
fi

unset -f __chipyard_env_fail __chipyard_prepend_path 2>/dev/null || true
unset __chipyard_env_source
unset __chipyard_env_name
unset __chipyard_prompt
unset __chipyard_old_prompt
unset __DIR
true
EOT

    mv "$tmp_file" "$env_file"
}
